- readme.md
> add Juri to the list

- readme.md
> Add Farzad's blog to the list

- readme.md
> Adds Marius Schulz's blog

- readme.md
adding https://christianfei.com/
> add christianfei.com

- readme.md
Jessie Fazelle -> Jessie Frazelle
> Fix name typo

- readme.md
> I prefer having the `.` :)

- readme.md
> Add Colin Cummings

- readme.md
Number 1 user of StackOverflow as per reputation
> Added Jon Skeet Blog

- readme.md
> Added Matthias Noback's -  "About software development" blog

- readme.md
Add [Huy Nguyen's blog](https://www.huy.dev).
> Add Huy Nguyen's blog

- readme.md
> Feat: add luetkemj.github.io

- readme.md
> Add Dave Chaney

- readme.md
> Adds Fatih Arslan

- readme.md
Adding entry for my personal blog. Mostly tech and productivity related topics. Been doing a blog post every month since 2016.
> Add entry for Kevin Jalbert

- readme.md
> Adds Russ Cox

- readme.md
ft. content on design, react, and general devvery. Thanks!
https://mike.biful.co
> Adds Mike Bifulco

- readme.md
Hi
Request to add my [blog](https://blog.amanpratapsingh.in) also in the list.
Aman
> Add Aman Pratap Singh's blog.

- readme.md
I share tech things I have been playing with.
> Add tech blog of Tony Xu

- readme.md
A kindly request to add my personal blog.
> Add personal blog of Mustafa Çalap

- readme.md
Add my brand new **tech and design-oriented** [blog](https://raptis.wtf/blog) 🍻
Topics I'm gonna cover: 
- Productivity
- UX/UI design
- Coding and Designing workflow
- ReactJS and Front-end development
> Add Dimitris Raptis

- readme.md
Added Shodipo Ayomide personal blog
> Added Shodipo Ayomide personal blog

- readme.md
What a neat repo! I recognize a lot of names of blogs I love.
I write about building web applications, software careers, and general computer science topics. All on my [Jekyll-based blog](https://healeycodes.github.io/).
Thank you for maintaining this.
> Add Andrew Healey

- readme.md
> Add Thomas Hunter

- readme.md
Hello! 
Great project! I really like to read personal blogs. Some of them are really good and full of cool stories and experiences.
Cheers!
> Add my personnal blog

- readme.md
This list would be even more awesome with some information about the blogs listed here :)
> Add blog of Kevin Hirczy (nehalist.io)

- readme.md
I recently came across this nice repository and thought I'd add my blog, which I've started to post more frequently to. I hope it's of the required standard. 🙂
> Add Gideon Pyzer blog

- readme.md
David Walsh is a personal blog that publishes articles on various front-end and back-end technologies for web development such as AJAX, Canvas & SVG, CSS, Dojo, Firefox OS, HTML5, JavaScript, jQuery, Node.js, etc. If you are particularly passionate about software development, you will definitely like David Walsh's blog.
> added David Walsh

- readme.md
An interesting and insightful list. Would love to get my blog on there too if possible!
> Added Jeremy Shaw blog

- readme.md
Got a shorter domain name, and the older one is about to expire.
> Updated my entry for Alexandru-Paul Copil

- readme.md
It would be cool, if my site can be included. I write about different things, like random personal experiences or tech stuff.
> Add jlelse.blog

- readme.md
My personal blog, normally about infosec, pentesting, and privacy.
https://jarv.is/notes/
Thanks in advance! 😊
> Add Jake Jarvis's blog

- readme.md
Main topic are: python, javascript, functional programming. 
I also write a little bit about management.
https://sobolevn.me/
> Adds Nikita Sobolev's blog

- readme.md
> Add Peter Bengtsson

- readme.md
This my personal blog in both Chinese and English. Now, homepage, about page and resume page is available in English, more English posts are on the way. Most of posts are machine learning related, and some are my opinions on books, movies and life. Currently, I am working on intelligent agriculture, thus it will get more posts in this subject.
> Add Leo Van's Blog

- readme.md
> Update Andrew Healey URL

- readme.md
Jake is a developer advocate at Google and writes awesome blogs.
> add Jake Archibald

- readme.md
Add https://girisagar46.github.io/
> Add Sagar Giri

- readme.md
Personal Blog:  codewithhugo.com
> Add Hugo Di Francesco personal blog

- readme.md
Personal tech blog https://blog.jibin.tech
> Add Jibin Thomas blog

- readme.md
> Add my personal site (tik.dev)

- readme.md
> Add my blog/website

- readme.md
Hello
First of all, thank you for this list which is really interesting !
This PR is adding a link to my own website where I try to post when I have something interesting to share. I hope it fits the requirements to be listed here :).
Thanks
> Add code-trotter blog

- readme.md
> Add madelinemiller.dev

- readme.md
Thanks for maintaining this list!
> Add John Wright Stanly's blog
